name: Build and Release

on:
  push:
    branches:
      - master  # Adjust this as necessary, e.g., to tags instead of main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # Specify your .NET version here

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-restore --output publish/
        
      - name: Archive production artifacts
        run: |
          tar -cvzf YoutubeDownloader.tar.gz -C publish/ YoutubeDownloader

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}  # Setting the environment variable for authentication
        with:
          tag_name: YoutubeDownloder-v1.0.1
          release_name: Release YoutubeDownloder-v1.0.1
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}  # Ensure this step also uses the PAT for authentication
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./YoutubeDownloader.tar.gz
          asset_name: YoutubeDownloader.tar.gz
          asset_content_type: application/gzip
